bq_dbt:
  outputs:
    prod:
      dataset: roman_dbt_prod
      fixed_retries: 1
      keyfile: /home/src/cfk.json
      location: us-west1
      method: service-account
      priority: interactive
      project: coral-firefly-411510 
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: prod      
